apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-task-dev
  namespace: mq
spec:
  params:
    - name: git-mqsc-clone
    - name: mqsc-subdirectory
    - name: GIT_SECRET
    - name: source-dir
    - name: git-cli-image
    - name: kustomize-subdirectory
    - name: git-kustomize-clone
    - name: kustommize-git-branch

  workspaces:
    - name: source
      mountPath: $(params.source-dir)

  # volumes:
  #   - name: source
  #     persistentVolumeClaim:
  #       claimName: tekton-pvc
  # stepTemplate:
  #   volumeMounts:
  #     - name: source
  #       mountPath: $(params.source-dir)
  steps:
    - name: git-pull
      image: $(params.git-cli-image)
      env:
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: $(params.GIT_SECRET)
              key: password
              optional: true
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: $(params.GIT_SECRET)
              key: username
              optional: true
        - name: GIT_EMAIL
          valueFrom:
            secretKeyRef:
              name: $(params.GIT_SECRET)
              key: email
              optional: true
      resources: {}
      script: |
        git config --global user.email "$GIT_EMAIL"
        git config --global user.name "$GIT_USERNAME"

        $(params.git-mqsc-clone)
        $(params.git-kustomize-clone)
        rm -rf $(params.mqsc-subdirectory)/.git

        cd $(params.mqsc-subdirectory)

        # copy UAT dynamic mqsc to PTE and PRD
        cp -n -R uat/ pte/
        cp -n -R uat/ prd/

        for env in dynamic-mqsc/*
        do   
          for qm in $env/*
          do
              echo `cat $qm/.env`
              export `cat $qm/.env`
              eval "echo \"$(cat $qm/dynamic.mqsc)\"" > $qm/dynamic.mqsc
          done
        done

        cd ..
        echo `cat $(params.mqsc-subdirectory)/dev/qm01/dynamic.mqsc`


        cp -R $(params.mqsc-subdirectory)/dev $(params.kustomize-subdirectory)/
        cp -R $(params.mqsc-subdirectory)/sit $(params.kustomize-subdirectory)/
        cp -R $(params.mqsc-subdirectory)/uat $(params.kustomize-subdirectory)/
        cp -R $(params.mqsc-subdirectory)/pte $(params.kustomize-subdirectory)/
        cp -R $(params.mqsc-subdirectory)/prd $(params.kustomize-subdirectory)/

        # cd $(params.kustomize-subdirectory)
        # git add .
        # git commit -m "tekton added dynamic mqsc"
        # git push origin $(params.kustommize-git-branch)

      workingDir: $(params.source-dir)
